name: FloodedWorld
version: '${version}'

main: club.ironpvp.floodedWorld.FloodedWorld
api-version: '1.21.11'
load: STARTUP
folia-supported: true

authors: [ue_rami]

commands:
  nightvision:
    aliases: [nv]